# Generated by Django 2.2.14 on 2021-02-05 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mvp_app', '0004_project_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
